export const EVENT_TYPES_CONFIG = [
  {
    value: "class",
    label: "Clase",
    icon: "school",
    category: "academic",
    requiresClass: true,
    supportsClassroom: true,
    supportsRecurrence: true,
  },
  {
    value: "tarea",
    label: "Tarea",
    icon: "clipboard",
    category: "academic",
    requiresClass: false,
    supportsClassroom: false,
    supportsRecurrence: false,
  },
  {
    value: "laboratorio",
    label: "Laboratorio",
    icon: "flask",
    category: "academic",
    requiresClass: false,
    supportsClassroom: true,
    supportsRecurrence: false,
  },
  {
    value: "quiz",
    label: "Quiz",
    icon: "document-text",
    category: "academic",
    requiresClass: false,
    supportsClassroom: true,
    supportsRecurrence: false,
  },
  {
    value: "parcial",
    label: "Parcial",
    icon: "document-text",
    category: "academic",
    requiresClass: false,
    supportsClassroom: true,
    supportsRecurrence: false,
  },
  {
    value: "examen_final",
    label: "Examen Final",
    icon: "document-text",
    category: "academic",
    requiresClass: false,
    supportsClassroom: true,
    supportsRecurrence: false,
  },
  {
    value: "proyecto",
    label: "Proyecto",
    icon: "folder",
    category: "academic",
    requiresClass: false,
    supportsClassroom: false,
    supportsRecurrence: false,
  },
  {
    value: "practica",
    label: "Práctica",
    icon: "hammer",
    category: "academic",
    requiresClass: false,
    supportsClassroom: true,
    supportsRecurrence: false,
  },
  {
    value: "investigacion",
    label: "Investigación",
    icon: "search",
    category: "academic",
    requiresClass: false,
    supportsClassroom: false,
    supportsRecurrence: false,
  },
  {
    value: "charla",
    label: "Charla",
    icon: "megaphone",
    category: "academic",
    requiresClass: false,
    supportsClassroom: true,
    supportsRecurrence: false,
  },
  {
    value: "dia_libre",
    label: "Día Libre",
    icon: "calendar",
    category: "general_event",
    requiresClass: false,
    supportsClassroom: false,
    supportsRecurrence: false,
  },
  {
    value: "recordatorio",
    label: "Recordatorio",
    icon: "bell",
    category: "general_event",
    requiresClass: false,
    supportsClassroom: false,
    supportsRecurrence: false,
  },
] as const

export const REMINDER_OPTIONS = [
  { value: 0, label: "Sin recordatorio" },
  { value: 5, label: "5 minutos" },
  { value: 15, label: "15 minutos" },
  { value: 30, label: "30 minutos" },
  { value: 60, label: "1 hora" },
  { value: 120, label: "2 horas" },
  { value: 1440, label: "1 día" },
] as const

export const RECURRENCE_PATTERNS = {
  DAILY: "daily",
  WEEKLY: "weekly",
  MONTHLY: "monthly",
} as const

export const EVENT_CATEGORIES = {
  ACADEMIC: "academic",
  GENERAL_EVENT: "general_event",
} as const
